/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalysisRouteImport } from './routes/app.analysis'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppRoundsRouteImport } from './routes/app.rounds'
import { Route as AppSettlementRouteImport } from './routes/app.settlement'
import { Route as AppTradeRouteImport } from './routes/app.trade'
import { Route as AppStockSymbolRouteImport } from './routes/app.stock.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppRoundsRoute = AppRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementRoute = AppSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeRoute = AppTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AppRoute,
} as any)
const AppStockSymbolRoute = AppStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/market': typeof AppMarketRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/rounds': typeof AppRoundsRoute
  '/app/settlement': typeof AppSettlementRoute
  '/app/trade': typeof AppTradeRoute
  '/app/': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/market': typeof AppMarketRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/rounds': typeof AppRoundsRoute
  '/app/settlement': typeof AppSettlementRoute
  '/app/trade': typeof AppTradeRoute
  '/app': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/market': typeof AppMarketRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/rounds': typeof AppRoundsRoute
  '/app/settlement': typeof AppSettlementRoute
  '/app/trade': typeof AppTradeRoute
  '/app/': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/how-it-works'
    | '/leaderboard'
    | '/login'
    | '/app/analysis'
    | '/app/market'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/rounds'
    | '/app/settlement'
    | '/app/trade'
    | '/app/'
    | '/app/stock/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/leaderboard'
    | '/login'
    | '/app/analysis'
    | '/app/market'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/rounds'
    | '/app/settlement'
    | '/app/trade'
    | '/app'
    | '/app/stock/$symbol'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/how-it-works'
    | '/leaderboard'
    | '/login'
    | '/app/analysis'
    | '/app/market'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/rounds'
    | '/app/settlement'
    | '/app/trade'
    | '/app/'
    | '/app/stock/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analysis': {
      id: '/app/analysis'
      path: '/analysis'
      fullPath: '/app/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rounds': {
      id: '/app/rounds'
      path: '/rounds'
      fullPath: '/app/rounds'
      preLoaderRoute: typeof AppRoundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settlement': {
      id: '/app/settlement'
      path: '/settlement'
      fullPath: '/app/settlement'
      preLoaderRoute: typeof AppSettlementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trade': {
      id: '/app/trade'
      path: '/trade'
      fullPath: '/app/trade'
      preLoaderRoute: typeof AppTradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock/$symbol': {
      id: '/app/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/app/stock/$symbol'
      preLoaderRoute: typeof AppStockSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppMarketRoute: typeof AppMarketRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppRiskRoute: typeof AppRiskRoute
  AppRoundsRoute: typeof AppRoundsRoute
  AppSettlementRoute: typeof AppSettlementRoute
  AppTradeRoute: typeof AppTradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStockSymbolRoute: typeof AppStockSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysisRoute: AppAnalysisRoute,
  AppMarketRoute: AppMarketRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppRiskRoute: AppRiskRoute,
  AppRoundsRoute: AppRoundsRoute,
  AppSettlementRoute: AppSettlementRoute,
  AppTradeRoute: AppTradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppStockSymbolRoute: AppStockSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
